services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: ["go", "run", "./cmd/api"]
    volumes:
      - ./backend:/app

  bot:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: ["go", "run", "./cmd/bot"]
    volumes:
      - ./backend:/app
